//! AI Junk Cleanup module for Dev Janitor v2
//! Detects and cleans up files generated by AI coding assistants

use rayon::prelude::*;
use serde::{Deserialize, Serialize};
use std::cmp::Reverse;
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use walkdir::WalkDir;

/// Represents an AI junk file detected
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AiJunkFile {
    pub id: String,
    pub name: String,
    pub path: String,
    pub size: u64,
    pub size_display: String,
    pub junk_type: String,
    pub reason: String,
}

/// Scan mode for AI junk detection
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ScanMode {
    FullDisk,
    Directory(String),
}

/// AI tool related patterns
const AI_TOOL_PATTERNS: &[(&str, &str)] = &[
    // Aider ephemeral files
    (".aider.chat.history.md", "Aider chat history"),
    (".aider.input.history", "Aider input history"),
    (".aider.tags.cache", "Aider tags cache"),
    // Claude output artifacts
    ("claude_output", "Claude output directory"),
    // Copilot
    (".copilot/session-state", "GitHub Copilot CLI session state"),
    (
        ".copilot/session-store.db",
        "GitHub Copilot CLI session store",
    ),
    // Goose
    (".config/goose/history.txt", "Goose command history"),
    (".local/share/goose/sessions", "Goose session records"),
    (".local/state/goose/logs", "Goose logs"),
    // OpenHands
    (".openhands/conversations", "OpenHands conversation history"),
    // Qwen Code
    (".qwen/.cache", "Qwen Code cache"),
    // Cline
    (".cline/cache", "Cline cache"),
    (".cline/history", "Cline history"),
    (".config/cline/cache", "Cline cache"),
    (".config/cline/history", "Cline history"),
    // Amp
    (".amp/cache", "Amp cache"),
    (".config/amp/cache", "Amp cache"),
    // Crush
    (".crush/cache", "Crush cache"),
    (".config/crush/cache", "Crush cache"),
    // Codeium
    (".codeium", "Codeium AI cache"),
    // Tabnine
    (".tabnine", "Tabnine AI cache"),
    // Windsurf
    (".windsurf", "Windsurf AI cache"),
    // Amazon Q / CodeWhisperer
    (".amazonq/cache", "Amazon Q Developer cache"),
    (".amazonq/history", "Amazon Q Developer history"),
    (".aws/amazonq/cache", "Amazon Q cache"),
    (".aws/amazonq/history", "Amazon Q history"),
    (".aws/codewhisperer/cache", "CodeWhisperer cache"),
    // Generic AI patterns
    (".ai_cache", "Generic AI cache"),
    (".llm_cache", "LLM cache directory"),
];

/// Temporary file patterns
const TEMP_FILE_PATTERNS: &[(&str, &str)] = &[
    (".tmp", "Temporary file"),
    (".temp", "Temporary file"),
    (".bak", "Backup file"),
    (".backup", "Backup file"),
    (".orig", "Original file backup"),
    (".old", "Old file"),
    ("~", "Editor temporary file"),
    (".swp", "Vim swap file"),
    (".swo", "Vim swap file"),
    (".DS_Store", "macOS metadata"),
    ("Thumbs.db", "Windows thumbnail cache"),
    ("desktop.ini", "Windows desktop config"),
];

/// Whitelist - files/directories to never delete
const WHITELIST_EXTENSIONS: &[&str] = &[
    // Audio
    "mp3", "wav", "flac", "aac", "ogg", "wma", "m4a", // Video
    "mp4", "avi", "mkv", "mov", "wmv", "flv", "webm", // Documents
    "pdf", "doc", "docx", "xls", "xlsx", "ppt", "pptx", "odt", "ods", "odp",
    // Images (important ones)
    "psd", "ai", "raw", "cr2", "nef", // Archives
    "zip", "rar", "7z", "tar", "gz",
];

const WHITELIST_DIRECTORIES: &[&str] = &[
    "node_modules",
    ".git",
    ".svn",
    "vendor",
    "venv",
    ".venv",
    "target",
    "__pycache__",
    "dist",
    "build",
];

/// Clamp depth when the user tries to scan the filesystem root
const ROOT_SCAN_MAX_DEPTH: usize = 8;

/// Format bytes to human readable string
fn format_size(bytes: u64) -> String {
    const KB: u64 = 1024;
    const MB: u64 = KB * 1024;
    const GB: u64 = MB * 1024;

    if bytes >= GB {
        format!("{:.2} GB", bytes as f64 / GB as f64)
    } else if bytes >= MB {
        format!("{:.2} MB", bytes as f64 / MB as f64)
    } else if bytes >= KB {
        format!("{:.2} KB", bytes as f64 / KB as f64)
    } else {
        format!("{} B", bytes)
    }
}

/// Get directory size
fn get_size(path: &PathBuf) -> u64 {
    if path.is_file() {
        path.metadata().map(|m| m.len()).unwrap_or(0)
    } else {
        WalkDir::new(path)
            .into_iter()
            .filter_map(|e| e.ok())
            .filter_map(|e| e.metadata().ok())
            .filter(|m| m.is_file())
            .map(|m| m.len())
            .sum()
    }
}

/// Check if a file/directory should be whitelisted
fn is_whitelisted(path: &Path) -> bool {
    let name = path
        .file_name()
        .map(|n| n.to_string_lossy().to_lowercase())
        .unwrap_or_default();

    // Check directory whitelist
    if path.is_dir() {
        for wl_dir in WHITELIST_DIRECTORIES {
            if name == *wl_dir {
                return true;
            }
        }
    }

    // Check extension whitelist
    if let Some(ext) = path.extension() {
        let ext_lower = ext.to_string_lossy().to_lowercase();
        if WHITELIST_EXTENSIONS.contains(&ext_lower.as_str()) {
            return true;
        }
    }

    false
}

/// Check if a file matches AI tool patterns
fn check_ai_tool_pattern(path: &Path) -> Option<(&'static str, &'static str)> {
    let name = path
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_default();

    for (pattern, reason) in AI_TOOL_PATTERNS {
        if !pattern.contains('/') && (name == *pattern || name.starts_with(pattern)) {
            return Some((pattern, reason));
        }
    }

    // Check path-based patterns such as `.qwen/.cache` against both the
    // directory itself and files below it.
    let path_str = path.to_string_lossy().replace('\\', "/").to_lowercase();
    for (pattern, reason) in AI_TOOL_PATTERNS {
        if !pattern.contains('/') {
            continue;
        }

        let pattern_lower = pattern.to_ascii_lowercase();
        if path_str == *pattern
            || path_str.ends_with(&format!("/{pattern_lower}"))
            || path_str.contains(&format!("/{pattern_lower}/"))
        {
            return Some((pattern, reason));
        }
    }

    None
}

/// Check if a file matches temp file patterns
fn check_temp_pattern(path: &Path) -> Option<(&'static str, &'static str)> {
    let name = path
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_default();

    for (pattern, reason) in TEMP_FILE_PATTERNS {
        if name == *pattern || name.ends_with(pattern) {
            return Some((pattern, reason));
        }
    }

    None
}

/// Check for anomalous files (zero-byte, very short names, etc.)
fn check_anomalous(path: &Path) -> Option<String> {
    let name = path
        .file_name()
        .map(|n| n.to_string_lossy().to_string())
        .unwrap_or_default();

    // Zero-byte files (except known empty files)
    if path.is_file() {
        if let Ok(meta) = path.metadata() {
            if meta.len() == 0 && !name.starts_with(".git") && name != ".gitkeep" {
                return Some("Zero-byte file".to_string());
            }
        }
    }

    // Very short names that look suspicious
    if name.len() == 1
        && !name
            .chars()
            .next()
            .map(|c| c.is_alphanumeric())
            .unwrap_or(false)
    {
        return Some("Suspicious single-character name".to_string());
    }

    // Names with only special characters
    if !name.is_empty()
        && name
            .chars()
            .all(|c| !c.is_alphanumeric() && c != '.' && c != '_' && c != '-')
    {
        return Some("Name contains only special characters".to_string());
    }

    None
}

fn user_home_dir() -> Option<PathBuf> {
    #[cfg(target_os = "windows")]
    {
        if let Some(profile) = std::env::var_os("USERPROFILE") {
            return Some(PathBuf::from(profile));
        }
        if let (Some(drive), Some(path)) =
            (std::env::var_os("HOMEDRIVE"), std::env::var_os("HOMEPATH"))
        {
            let combined = format!("{}{}", drive.to_string_lossy(), path.to_string_lossy());
            return Some(PathBuf::from(combined));
        }
        None
    }

    #[cfg(not(target_os = "windows"))]
    {
        std::env::var_os("HOME").map(PathBuf::from)
    }
}

fn is_root_path(path: &Path) -> bool {
    path.parent().is_none()
}

fn canonicalize_existing_path(path: &Path) -> Result<PathBuf, String> {
    let metadata = fs::symlink_metadata(path)
        .map_err(|error| format!("Failed to inspect {}: {}", path.display(), error))?;
    if metadata.file_type().is_symlink() {
        return Err(format!(
            "Refusing to delete symlink path: {}",
            path.display()
        ));
    }

    path.canonicalize()
        .map_err(|error| format!("Failed to resolve {}: {}", path.display(), error))
}

fn is_root_or_home_path(path: &Path) -> bool {
    if is_root_path(path) {
        return true;
    }

    user_home_dir()
        .and_then(|home| home.canonicalize().ok())
        .map(|home| home == path)
        .unwrap_or(false)
}

fn validate_ai_junk_delete_target(path: &Path) -> Result<PathBuf, String> {
    let canonical = canonicalize_existing_path(path)?;

    if is_root_or_home_path(&canonical) {
        return Err(format!(
            "Refusing to delete unsafe path: {}",
            canonical.display()
        ));
    }

    if is_whitelisted(&canonical) {
        return Err(format!(
            "Refusing to delete whitelisted path: {}",
            canonical.display()
        ));
    }

    let looks_like_junk = check_ai_tool_pattern(&canonical).is_some()
        || check_temp_pattern(&canonical).is_some()
        || check_anomalous(&canonical).is_some();

    if looks_like_junk {
        Ok(canonical)
    } else {
        Err(format!(
            "Path is not a recognized AI junk target: {}",
            canonical.display()
        ))
    }
}

fn make_junk_file(
    id_prefix: &str,
    path: &Path,
    name: String,
    size: u64,
    junk_type: &str,
    reason: String,
) -> AiJunkFile {
    AiJunkFile {
        id: format!(
            "{}_{}",
            id_prefix,
            path.to_string_lossy().replace(['\\', '/', ' '], "_")
        ),
        name,
        path: path.to_string_lossy().to_string(),
        size,
        size_display: format_size(size),
        junk_type: junk_type.to_string(),
        reason,
    }
}

fn scan_target(root: &Path, max_depth: usize) -> Vec<AiJunkFile> {
    let mut junk_files = Vec::new();
    let mut entries = WalkDir::new(root).max_depth(max_depth).into_iter();

    while let Some(entry_result) = entries.next() {
        let Ok(entry) = entry_result else {
            continue;
        };
        let path = entry.path();

        if is_whitelisted(path) {
            if entry.file_type().is_dir() {
                entries.skip_current_dir();
            }
            continue;
        }

        let name = entry.file_name().to_string_lossy().to_string();

        if let Some((pattern, reason)) = check_ai_tool_pattern(path) {
            let path_buf = path.to_path_buf();
            let size = get_size(&path_buf);
            junk_files.push(make_junk_file(
                "ai",
                path,
                name,
                size,
                "ai_tool",
                format!("AI Tool: {} - {}", pattern, reason),
            ));
            if entry.file_type().is_dir() {
                entries.skip_current_dir();
            }
            continue;
        }

        if let Some((pattern, reason)) = check_temp_pattern(path) {
            let path_buf = path.to_path_buf();
            let size = get_size(&path_buf);
            junk_files.push(make_junk_file(
                "temp",
                path,
                name,
                size,
                "temp_file",
                format!("Temp: {} - {}", pattern, reason),
            ));
            if entry.file_type().is_dir() {
                entries.skip_current_dir();
            }
            continue;
        }

        if let Some(reason) = check_anomalous(path) {
            let path_buf = path.to_path_buf();
            let size = get_size(&path_buf);
            junk_files.push(make_junk_file(
                "anomaly",
                path,
                name,
                size,
                "anomalous",
                reason,
            ));
            if entry.file_type().is_dir() {
                entries.skip_current_dir();
            }
        }
    }

    junk_files
}

/// Scan a directory for AI junk files
pub fn scan_ai_junk(root_path: &str, max_depth: usize) -> Vec<AiJunkFile> {
    let root = PathBuf::from(root_path);
    if !root.exists() {
        return Vec::new();
    }

    let mut effective_depth = max_depth;
    let mut targets = vec![root.clone()];

    if is_root_path(&root) {
        effective_depth = effective_depth.min(ROOT_SCAN_MAX_DEPTH);
        if let Some(home) = user_home_dir() {
            if home.exists() {
                targets = vec![home];
            }
        }
    }

    let mut junk_files: Vec<AiJunkFile> = targets
        .par_iter()
        .flat_map(|target| scan_target(target, effective_depth))
        .collect();

    // De-duplicate by full path to avoid repeats when targets overlap
    let mut by_path: HashMap<String, AiJunkFile> = HashMap::new();
    for file in junk_files.drain(..) {
        by_path.insert(file.path.clone(), file);
    }
    let mut junk_files: Vec<AiJunkFile> = by_path.into_values().collect();

    // Sort by size descending
    junk_files.sort_by_key(|file| Reverse(file.size));

    // Assign sequential IDs
    for (id_counter, file) in junk_files.iter_mut().enumerate() {
        file.id = format!("junk_{}", id_counter);
    }

    junk_files
}

/// Delete an AI junk file with permission retry
pub fn delete_ai_junk(path: &str) -> Result<String, String> {
    let file_path = PathBuf::from(path);

    if !file_path.exists() {
        return Err(format!("File does not exist: {}", path));
    }

    let file_path = validate_ai_junk_delete_target(&file_path)?;

    // Check for Windows reserved names
    #[cfg(target_os = "windows")]
    {
        let name = file_path
            .file_name()
            .map(|n| n.to_string_lossy().to_lowercase())
            .unwrap_or_default();
        let reserved = [
            "con", "prn", "aux", "nul", "com1", "com2", "com3", "com4", "com5", "com6", "com7",
            "com8", "com9", "lpt1", "lpt2", "lpt3", "lpt4", "lpt5", "lpt6", "lpt7", "lpt8", "lpt9",
        ];
        let name_without_ext = name.split('.').next().unwrap_or(&name);
        if reserved.contains(&name_without_ext) {
            return Err(format!("Cannot delete Windows reserved name: {}", path));
        }
    }

    // Get size before deletion
    let size = get_size(&file_path);

    // Try to delete
    let result = if file_path.is_dir() {
        fs::remove_dir_all(&file_path)
    } else {
        fs::remove_file(&file_path)
    };

    match result {
        Ok(_) => Ok(format!(
            "Successfully deleted {} (freed {})",
            path,
            format_size(size)
        )),
        Err(e) => {
            // Try with permission fix
            #[cfg(target_os = "windows")]
            {
                if fix_permissions_and_delete(&file_path).is_ok() {
                    return Ok(format!(
                        "Successfully deleted {} (freed {})",
                        path,
                        format_size(size)
                    ));
                }
            }

            #[cfg(unix)]
            {
                if chmod_and_delete(&file_path).is_ok() {
                    return Ok(format!(
                        "Successfully deleted {} (freed {})",
                        path,
                        format_size(size)
                    ));
                }
            }

            Err(format!("Failed to delete {}: {}", path, e))
        }
    }
}

#[cfg(target_os = "windows")]
#[allow(clippy::permissions_set_readonly_false)]
fn fix_permissions_and_delete(path: &PathBuf) -> std::io::Result<()> {
    use std::os::windows::fs::MetadataExt;

    // Remove readonly attribute
    if let Ok(metadata) = fs::metadata(path) {
        if metadata.file_attributes() & 1 != 0 {
            let mut perms = metadata.permissions();
            perms.set_readonly(false);
            fs::set_permissions(path, perms)?;
        }
    }

    if path.is_dir() {
        // Recursively fix permissions
        for entry in WalkDir::new(path).into_iter().filter_map(|e| e.ok()) {
            if let Ok(metadata) = fs::metadata(entry.path()) {
                if metadata.file_attributes() & 1 != 0 {
                    let mut perms = metadata.permissions();
                    perms.set_readonly(false);
                    let _ = fs::set_permissions(entry.path(), perms);
                }
            }
        }
        fs::remove_dir_all(path)
    } else {
        fs::remove_file(path)
    }
}

#[cfg(unix)]
fn chmod_and_delete(path: &PathBuf) -> std::io::Result<()> {
    use std::os::unix::fs::PermissionsExt;

    // Set write permission
    if let Ok(metadata) = fs::metadata(path) {
        let mut perms = metadata.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(path, perms)?;
    }

    if path.is_dir() {
        fs::remove_dir_all(path)
    } else {
        fs::remove_file(path)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn temp_project(name: &str) -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let dir = std::env::temp_dir().join(format!("dev-janitor-ai-cleanup-{name}-{nanos}"));
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn ignores_kiro_project_metadata() {
        let project = temp_project("kiro");
        fs::write(project.join("package.json"), "{}\n").unwrap();
        fs::create_dir_all(project.join(".kiro/steering")).unwrap();
        fs::write(project.join(".kiro/steering/product.md"), "project rules").unwrap();

        let results = scan_ai_junk(project.to_str().unwrap(), 3);
        assert!(
            !results.iter().any(|f| f.path.contains(".kiro")),
            ".kiro project metadata should not be treated as AI junk"
        );

        fs::remove_dir_all(project).unwrap();
    }

    #[test]
    fn ignores_active_ai_project_configs() {
        let project = temp_project("configs");
        fs::write(project.join("package.json"), "{}\n").unwrap();
        fs::create_dir_all(project.join(".claude")).unwrap();
        fs::write(project.join(".claude/settings.json"), "{}\n").unwrap();
        fs::create_dir_all(project.join(".codex")).unwrap();
        fs::write(project.join(".codex/config.toml"), "model = \"gpt-5.4\"\n").unwrap();
        fs::create_dir_all(project.join(".copilot")).unwrap();
        fs::write(project.join(".copilot/config.json"), "{}\n").unwrap();
        fs::write(project.join(".copilot/settings.json"), "{}\n").unwrap();
        fs::create_dir_all(project.join(".config/github-copilot")).unwrap();
        fs::write(project.join(".config/github-copilot/config.json"), "{}\n").unwrap();
        fs::create_dir_all(project.join(".cursor")).unwrap();
        fs::write(project.join(".cursor/cli-config.json"), "{}\n").unwrap();
        fs::create_dir_all(project.join(".continue")).unwrap();
        fs::write(project.join(".continue/config.yaml"), "name: test\n").unwrap();
        fs::create_dir_all(project.join(".opencode/commands")).unwrap();
        fs::write(project.join(".opencode/commands/fix.md"), "# command\n").unwrap();
        fs::create_dir_all(project.join(".gemini")).unwrap();
        fs::write(project.join(".gemini/settings.json"), "{}\n").unwrap();

        let results = scan_ai_junk(project.to_str().unwrap(), 4);
        let result_paths: Vec<_> = results.iter().map(|file| file.path.as_str()).collect();

        assert!(
            !result_paths.iter().any(|path| path.contains(".claude")),
            ".claude project settings should not be treated as AI junk"
        );
        assert!(
            !result_paths.iter().any(|path| path.contains(".codex")),
            ".codex project settings should not be treated as AI junk"
        );
        assert!(
            !result_paths
                .iter()
                .any(|path| path.contains(".copilot") || path.contains(".config/github-copilot")),
            "GitHub Copilot configuration should not be treated as AI junk"
        );
        assert!(
            !result_paths.iter().any(|path| path.contains(".cursor")),
            ".cursor project settings should not be treated as AI junk"
        );
        assert!(
            !result_paths.iter().any(|path| path.contains(".continue")),
            ".continue project settings should not be treated as AI junk"
        );
        assert!(
            !result_paths.iter().any(|path| path.contains(".opencode")),
            ".opencode project settings should not be treated as AI junk"
        );
        assert!(
            !result_paths.iter().any(|path| path.contains(".gemini")),
            ".gemini project settings should not be treated as AI junk"
        );

        fs::remove_dir_all(project).unwrap();
    }

    #[test]
    fn ignores_new_active_ai_project_configs() {
        let project = temp_project("new-configs");
        fs::write(project.join("package.json"), "{}\n").unwrap();
        fs::create_dir_all(project.join(".qwen")).unwrap();
        fs::write(project.join(".qwen/settings.json"), "{}\n").unwrap();
        fs::create_dir_all(project.join(".cline")).unwrap();
        fs::write(project.join(".cline/settings.json"), "{}\n").unwrap();
        fs::create_dir_all(project.join(".amp")).unwrap();
        fs::write(project.join(".amp/settings.json"), "{}\n").unwrap();
        fs::create_dir_all(project.join(".crush")).unwrap();
        fs::write(project.join(".crush/config.json"), "{}\n").unwrap();
        fs::create_dir_all(project.join(".amazonq")).unwrap();
        fs::write(project.join(".amazonq/mcp.json"), "{}\n").unwrap();
        fs::create_dir_all(project.join(".augment")).unwrap();
        fs::write(project.join(".augment/settings.json"), "{}\n").unwrap();
        fs::create_dir_all(project.join(".config/kilo")).unwrap();
        fs::write(project.join(".config/kilo/opencode.jsonc"), "{}\n").unwrap();
        fs::create_dir_all(project.join(".junie/mcp")).unwrap();
        fs::write(project.join(".junie/AGENTS.md"), "project instructions\n").unwrap();
        fs::write(project.join(".junie/mcp/mcp.json"), "{}\n").unwrap();
        fs::write(project.join(".goosehints"), "project hints").unwrap();
        fs::write(project.join("AGENT.md"), "project instructions").unwrap();
        fs::create_dir_all(project.join(".openhands/hooks")).unwrap();
        fs::write(project.join(".openhands/hooks.json"), "{}\n").unwrap();
        fs::write(project.join(".openhands/setup.sh"), "#!/bin/sh\n").unwrap();

        let results = scan_ai_junk(project.to_str().unwrap(), 4);
        let result_paths: Vec<_> = results.iter().map(|file| file.path.as_str()).collect();

        assert!(
            !result_paths.iter().any(|path| path.contains(".qwen")),
            ".qwen project settings should not be treated as AI junk"
        );
        assert!(
            !result_paths.iter().any(|path| path.contains(".cline")),
            ".cline project settings should not be treated as AI junk"
        );
        assert!(
            !result_paths.iter().any(|path| path.contains(".amp")),
            ".amp project settings should not be treated as AI junk"
        );
        assert!(
            !result_paths.iter().any(|path| path.contains(".crush")),
            ".crush project settings should not be treated as AI junk"
        );
        assert!(
            !result_paths.iter().any(|path| path.contains(".amazonq")),
            ".amazonq project settings should not be treated as AI junk"
        );
        assert!(
            !result_paths.iter().any(|path| path.contains(".augment")),
            ".augment project settings should not be treated as AI junk"
        );
        assert!(
            !result_paths
                .iter()
                .any(|path| path.contains(".config/kilo")),
            ".config/kilo project settings should not be treated as AI junk"
        );
        assert!(
            !result_paths.iter().any(|path| path.contains(".junie")),
            ".junie project settings should not be treated as AI junk"
        );
        assert!(
            !result_paths.iter().any(|path| path.contains(".goosehints")
                || path.contains("AGENT.md")
                || path.contains(".openhands/hooks")
                || path.contains(".openhands/setup.sh")),
            "Goose/OpenHands project instructions should not be treated as AI junk"
        );

        fs::remove_dir_all(project).unwrap();
    }

    #[test]
    fn detects_copilot_cli_session_targets_without_config_noise() {
        let project = temp_project("copilot-cli-session");
        fs::write(project.join("package.json"), "{}\n").unwrap();
        fs::create_dir_all(project.join(".copilot")).unwrap();
        fs::write(project.join(".copilot/config.json"), "{}\n").unwrap();
        fs::write(project.join(".copilot/settings.json"), "{}\n").unwrap();
        fs::create_dir_all(project.join(".config/github-copilot")).unwrap();
        fs::write(project.join(".config/github-copilot/config.json"), "{}\n").unwrap();

        let session_state = project.join(".copilot/session-state");
        let session_store = project.join(".copilot/session-store.db");
        fs::create_dir_all(&session_state).unwrap();
        fs::write(session_state.join("events.jsonl"), "{}\n").unwrap();
        fs::write(&session_store, "sqlite").unwrap();

        let results = scan_ai_junk(project.to_str().unwrap(), 4);
        let result_paths: Vec<_> = results.iter().map(|file| file.path.as_str()).collect();

        assert!(
            result_paths
                .iter()
                .any(|path| *path == session_state.to_string_lossy()),
            "Copilot CLI session-state should be detected as AI junk"
        );
        assert!(
            result_paths
                .iter()
                .any(|path| *path == session_store.to_string_lossy()),
            "Copilot CLI session-store.db should be detected as AI junk"
        );
        assert!(
            !result_paths.iter().any(|path| path.ends_with(".copilot")
                || path.ends_with(".copilot/config.json")
                || path.ends_with(".copilot/settings.json")
                || path.contains(".config/github-copilot")),
            "Copilot config directories and files should not be treated as AI junk"
        );

        fs::remove_dir_all(project).unwrap();
    }

    #[test]
    fn detects_goose_and_openhands_history_targets() {
        let project = temp_project("goose-openhands-history");
        fs::write(project.join("package.json"), "{}\n").unwrap();
        let goose_sessions = project.join(".local/share/goose/sessions");
        let goose_logs = project.join(".local/state/goose/logs");
        let openhands_conversations = project.join(".openhands/conversations");
        fs::create_dir_all(&goose_sessions).unwrap();
        fs::create_dir_all(&goose_logs).unwrap();
        fs::create_dir_all(&openhands_conversations).unwrap();
        fs::write(goose_sessions.join("sessions.db"), "sessions").unwrap();
        fs::write(goose_logs.join("cli.log"), "logs").unwrap();
        fs::write(openhands_conversations.join("conversation.json"), "{}\n").unwrap();

        let results = scan_ai_junk(project.to_str().unwrap(), 6);
        let result_paths: Vec<_> = results.iter().map(|file| file.path.as_str()).collect();

        assert!(
            result_paths
                .iter()
                .any(|path| *path == goose_sessions.to_string_lossy()),
            "Goose session records should be detected as AI junk"
        );
        assert!(
            result_paths
                .iter()
                .any(|path| *path == goose_logs.to_string_lossy()),
            "Goose logs should be detected as AI junk"
        );
        assert!(
            result_paths
                .iter()
                .any(|path| *path == openhands_conversations.to_string_lossy()),
            "OpenHands conversation history should be detected as AI junk"
        );

        fs::remove_dir_all(project).unwrap();
    }

    #[test]
    fn reports_matching_directory_once_without_descendant_duplicates() {
        let project = temp_project("dedupe-dir");
        fs::write(project.join("package.json"), "{}\n").unwrap();
        let history_dir = project.join(".cline/history");
        fs::create_dir_all(&history_dir).unwrap();
        fs::write(history_dir.join("session.tmp"), "temporary history").unwrap();

        let results = scan_ai_junk(project.to_str().unwrap(), 4);
        let matching_paths: Vec<_> = results
            .iter()
            .filter(|file| file.path.contains(".cline/history"))
            .map(|file| file.path.as_str())
            .collect();

        assert_eq!(
            matching_paths.len(),
            1,
            "a matched junk directory should be reported once without descendant duplicates"
        );
        assert_eq!(matching_paths[0], history_dir.to_string_lossy());

        fs::remove_dir_all(project).unwrap();
    }
}
